table dimcustomer
	lineageTag: 3ea78196-dfc5-4be2-b97a-9d1f3735a87b
	sourceLineageTag: [dbo].[dimcustomer]

	measure TotalSales = SUM(factsales[QuantitySold])
		formatString: 0
		lineageTag: 0f986da3-6685-4c0e-9a15-894d80619274

		changedProperty = Name

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 415dec93-be30-45bf-8a5c-d4b53ea5714f
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: a3028801-df45-42a7-a55d-01075be9a8ba
		sourceLineageTag: CustomerName
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column CustomerGender
		dataType: string
		lineageTag: a85813fb-edd6-4a96-986b-7d1d4e7fb70f
		sourceLineageTag: CustomerGender
		summarizeBy: none
		sourceColumn: CustomerGender

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: ea0ab726-240f-40f2-a0ca-e07e54437141
		sourceLineageTag: CustomerEmail
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column CustomerPhone
		dataType: string
		lineageTag: 4f712c09-229f-450e-8bdf-940a5832ac0d
		sourceLineageTag: CustomerPhone
		summarizeBy: none
		sourceColumn: CustomerPhone

		annotation SummarizationSetBy = Automatic

	column CustomerAddress
		dataType: string
		lineageTag: fe5db268-c9fa-4455-867c-c1e8094d4e19
		sourceLineageTag: CustomerAddress
		summarizeBy: none
		sourceColumn: CustomerAddress

		annotation SummarizationSetBy = Automatic

	column CustomerCity
		dataType: string
		lineageTag: d3efe461-3476-48a4-b89c-1c15ec2435d6
		sourceLineageTag: CustomerCity
		summarizeBy: none
		sourceColumn: CustomerCity

		annotation SummarizationSetBy = Automatic

	column CustomerState
		dataType: string
		lineageTag: 4c268774-8066-406c-b692-9f5c46dcade2
		sourceLineageTag: CustomerState
		summarizeBy: none
		sourceColumn: CustomerState

		annotation SummarizationSetBy = Automatic

	column CustomerZipCode
		dataType: string
		lineageTag: f2bbbd85-d769-4914-8e40-50ad3b176099
		sourceLineageTag: CustomerZipCode
		summarizeBy: none
		sourceColumn: CustomerZipCode

		annotation SummarizationSetBy = Automatic

	column CustomerCountry
		dataType: string
		lineageTag: f8df704e-12c1-449f-ba6d-80b1ae126e7e
		sourceLineageTag: CustomerCountry
		summarizeBy: none
		sourceColumn: CustomerCountry

		annotation SummarizationSetBy = Automatic

	partition dimcustomer = entity
		mode: directLake
		source
			entityName: dimcustomer
			expressionSource: 'DirectLake - CD005_Lakehouse'

